### ISSUE TITLE
Some PDF-files have chapters starting at 0

### ISSUE THREAD

**Issue by xpqz** [Dyalog/documentation#161]
The table of contents logic in the pdf maker does not treat top-level files as chapters:

```yml
nav:
  - Not a chapter but should be: chapter1.md
  - Is a chapter and should be:
     - Intro: intro/chapter2.md
```
