### ISSUE TITLE
Search does not pick up I-beams

### ISSUE THREAD

**Issue by xpqz** [Dyalog/documentation#187]
If you enter "1500⌶" in the search box, no results are returned.

**Comment by xpqz** [comment]
Use yaml front matter to add synonyms to boost the search results:

```yml
---
meta:
  - search:
      boost: 2
      exclude: false
      terms:
        - 1500⌶
---
```

Note: this impacts the PDF and CHM converters, which must be taught to ignore these sections.
